apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: my-applications-alerts
  namespace: flux-system
spec:
  summary: "state of my cluster"
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: '*'
  - kind: Kustomization
    name: '*'