apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'severity']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 40m
      receiver: slack
    receivers:
    - name: slack
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: monitoring
        send_resolved: true