apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  selector:
    app: kube-prometheus-stack-grafana
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 3000
