apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  selector:
    app: kube-prometheus-stack-operator
  type: LoadBalancer
  ports:
  - name: web
    port: 9090
    targetPort: 9090