---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: portfolio
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/gladysgodwin/my-website-portfolio

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: portfolio
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kustomize
  prune: false
  sourceRef:
    kind: GitRepository
    name: portfolio
  targetNamespace: app

